package com.fieldgrade.app.provenance

/**
 * Where a piece of data came from, and whether it is real.
 *
 * One job: classify and describe data sources. It reads nothing and draws
 * nothing — callers declare what they loaded, and the UI renders the verdict.
 *
 * This exists because the most dangerous failure mode in this project is not a
 * crash: it is somebody watching the simulation run, seeing a machine track a
 * design surface to 28 mm, and believing that says something about hardware.
 * It does not. The RTK track is generated. The existing ground is generated.
 * Both are good enough to prove the *code path* and prove nothing at all about
 * the *system*.
 *
 * So the app states it, in the app, continuously — not only in a README that
 * whoever is being shown the demo has not read.
 */
enum class Provenance {
    /** Measured or published by someone else; we did not invent it. */
    REAL,

    /** Generated by us. Proves a code path, never a system. */
    SYNTHETIC,

    /** We cannot tell. Treated as SYNTHETIC everywhere it matters. */
    UNKNOWN;

    val label: String
        get() = when (this) {
            REAL -> "REAL"
            SYNTHETIC -> "SYNTHETIC"
            UNKNOWN -> "UNVERIFIED"
        }
}

/** One input, named and classified. */
data class DataSource(
    val role: String,
    val name: String,
    val provenance: Provenance,
    val note: String = ""
) {
    override fun toString() = "$role: $name [${provenance.label}]"
}

/**
 * Everything the current session is running on.
 *
 * The verdict is deliberately pessimistic: one synthetic input makes the whole
 * session synthetic. A run is only as trustworthy as its least trustworthy
 * input, and averaging that away is how a demo quietly becomes a claim.
 */
class SessionProvenance(val sources: List<DataSource>) {

    val verdict: Provenance = when {
        sources.isEmpty() -> Provenance.UNKNOWN
        sources.any { it.provenance == Provenance.SYNTHETIC } -> Provenance.SYNTHETIC
        sources.any { it.provenance == Provenance.UNKNOWN } -> Provenance.UNKNOWN
        else -> Provenance.REAL
    }

    /** True only when every input is real. */
    val isAllReal: Boolean get() = verdict == Provenance.REAL

    val syntheticSources: List<DataSource>
        get() = sources.filter { it.provenance != Provenance.REAL }

    /**
     * The warning to show on screen, or null when everything is real.
     * Names the offending inputs — "synthetic" alone leaves the viewer guessing
     * which half of what they are looking at is invented.
     */
    fun banner(): String? {
        if (isAllReal) return null
        val offenders = syntheticSources.joinToString(", ") { it.role }
        return "${verdict.label} DATA — $offenders. Proves the code path, not the machine."
    }

    /** Multi-line detail for logs and the status panel. */
    fun describe(): String = buildString {
        append("data provenance: ${verdict.label}\n")
        for (s in sources) {
            append("  ${s.role.padEnd(10)} ${s.provenance.label.padEnd(10)} ${s.name}")
            if (s.note.isNotEmpty()) append("  (${s.note})")
            append('\n')
        }
    }

    companion object {
        /**
         * Classify by filename as a backstop.
         *
         * Deliberately fails **toward** SYNTHETIC: a file that does not announce
         * itself as real is not assumed to be. Mislabelling generated data as
         * measured is the dangerous direction; the reverse merely shows a warning
         * that should not be there.
         */
        fun classify(name: String): Provenance = when {
            name.contains("SYNTHETIC", ignoreCase = true) -> Provenance.SYNTHETIC
            name.contains("_sim", ignoreCase = true) -> Provenance.SYNTHETIC
            name.contains("demo", ignoreCase = true) -> Provenance.SYNTHETIC
            else -> Provenance.UNKNOWN
        }

        /** A source whose realness the caller can vouch for. */
        fun real(role: String, name: String, note: String = "") =
            DataSource(role, name, Provenance.REAL, note)

        /** A source the caller knows it generated. */
        fun synthetic(role: String, name: String, note: String = "") =
            DataSource(role, name, Provenance.SYNTHETIC, note)

        /** A source of unknown origin — classified by name, never assumed real. */
        fun fromName(role: String, name: String, note: String = "") =
            DataSource(role, name, classify(name), note)

        /** Everything generated: the no-data-files demo mode. */
        fun allSynthetic(reason: String) = SessionProvenance(
            listOf(DataSource("everything", reason, Provenance.SYNTHETIC))
        )
    }
}
