#!/usr/bin/env python3
"""Generate a SYNTHETIC existing-ground survey to pair with a design surface.

One job: design XYZ -> existing-ground XYZ.

The whole point of a levelling job is the difference between two surfaces:

    cut/fill  =  design  -  existing ground

Without an existing surface the app can show the operator the target, but not
how much work is left anywhere except directly under the blade. This produces
the missing half so the cut/fill map can be drawn across the whole field.

The output is **synthetic** and labelled `EXISTING` in the Code column. It is
generated by the same model `make_rtk_track.py` uses to place the machine, so
the track and the ground agree: what the map says needs cutting is what the
blade will find when it gets there. Replace it with a real survey export and
nothing downstream changes.

Usage:
    python tools/make_existing_ground.py design.xyz existing.xyz [--undulation 0.15]
"""
import argparse
import sys

from ground_model import ground_surface
from xyz_io import describe, read_xyz, write_xyz


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("design_xyz")
    ap.add_argument("outfile")
    ap.add_argument("--undulation", type=float, default=0.15,
                    help="ground roughness amplitude, m (default 0.15)")
    args = ap.parse_args(argv)

    design = read_xyz(args.design_xyz)
    if len(design) < 3:
        print(f"error: no usable points in {args.design_xyz}", file=sys.stderr)
        return 1

    plane, ground = ground_surface(design, args.undulation)
    write_xyz(args.outfile, ground, code="EXISTING")

    # The cut/fill this pairing implies, so the numbers are visible up front
    # rather than only discovered once the app draws them.
    diffs = [d[2] - g[2] for d, g in zip(design, ground)]
    cut = sum(1 for v in diffs if v < -0.025)
    fill = sum(1 for v in diffs if v > 0.025)
    on_grade = len(diffs) - cut - fill

    print(f"wrote {len(ground)} points -> {args.outfile}")
    print(f"  design    {describe(design)}")
    print(f"  existing  {describe(ground)}")
    print(f"  plane fit z = {plane[0]:.3f} + {plane[1]:.6f}*E + {plane[2]:.6f}*N")
    print(f"  cut/fill  {min(diffs) * 1000:+.0f} .. {max(diffs) * 1000:+.0f} mm")
    print(f"            {cut} pts need cut, {fill} need fill, "
          f"{on_grade} within 25 mm ({100.0 * on_grade / len(diffs):.1f}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
